### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoSuchFieldError: TRINKET

### ISSUE THREAD

**Issue by Icebomb12333** [Radient-Sora/Baubley-Heart-Canisters#8]
So, my 1.12.2 modded game crashes and your Baubley heart Canisters is in the stacktrace of this crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 8/14/18 3:50 PM
Description: Initializing game

java.lang.NoSuchFieldError: TRINKET
	at kiba.bhc.items.BaseHeartCanister.getBaubleType(BaseHeartCanister.java:31)
	at baubles.client.ClientEventHandler.tooltipEvent(ClientEventHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_230_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:325)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$328/28868570.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$330/2776300.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at kiba.bhc.items.BaseHeartCanister.getBaubleType(BaseHeartCanister.java:31)
	at baubles.client.ClientEventHandler.tooltipEvent(ClientEventHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_230_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:325)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$328/28868570.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$330/2776300.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 226107832 bytes (215 MB) / 1056964608 bytes (1008 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_C5 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version                  | Source                                        | Signature                                |
	|:----- |:------------------ |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCH   | mcp                | 9.42                     | minecraft.jar                                 | None                                     |
	| UCH   | FML                | 8.0.99.99                | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.4.2705             | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | rpghud             | 3.6.6.2                  | [1.12] RPG-HUD-3.6.6.2.jar                    | None                                     |
	| UCH   | baubles            | 1.5.2                    | Baubles-Mod-1.12.2.jar                        | None                                     |
	| UCH   | mantle             | 1.12-1.3.2.24            | Mantle-Mod-1.12.2.jar                         | None                                     |
	| UCH   | jei                | 4.8.0.114                | jei_1.12.2-4.8.0.114.jar                      | None                                     |
	| UCH   | tconstruct         | 1.12.2-2.10.0.81         | TConstruct-1.12.2-2.10.0.81.jar               | None                                     |
	| UCH   | bhc                | 1.2.1                    | baubley-heart-canisters-1.12.2-1.2.1.jar      | None                                     |
	| UCH   | biomesoplenty      | 7.0.1.2361               | BiomesOPlenty-1.12.2-7.0.1.2361-universal.jar | None                                     |
	| UCH   | guideapi           | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                   | None                                     |
	| UCH   | bloodmagic         | @VERSION@                | Blood-Magic-Mod-1.12.2.jar                    | None                                     |
	| UCH   | botania            | r1.10-354                | Botania-Mod-1.12.2.jar                        | None                                     |
	| UCH   | codechickenlib     | 3.1.6.339                | CodeChickenLib-1.12.2.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | fpsreducer         | 1.12.2-1.10.1            | FpsReducer-1.12.2.jar                         | None                                     |
	| UCH   | ichunutil          | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCH   | mocreatures        | 12.0.5                   | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCH   | morph              | 7.1.2                    | Morph-1.12.2.jar                              | None                                     |
	| UCH   | nei                | 2.4.1                    | Not-Enough-Items-1.12.2-Recommended.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | tinkertoolleveling | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar           | None                                     |
	| UCH   | twilightforest     | 3.7.424                  | Twilight-Forest-Mod-1.12.2.jar                | None                                     |
	| UCH   | uteamcore          | 1.3.0.72                 | u_team_core-1.12.2-1.3.0.72.jar               | None                                     |
	| UCH   | usefulbackpacks    | 1.2.0.8                  | useful_backpacks-1.12.2-1.2.0.8.jar           | None                                     |
	| UCH   | xaerominimap       | 1.13.8                   | Xaerosminimap1.12.2.jar                       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.0.0' Renderer: 'AMD Radeon R7 200 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.13431 Compatibility Profile Context 16.150.0.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Pentium(R) Dual-Core CPU E5200 @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C5
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13431 Compatibility Profile Context 16.150.0.0
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by Radient-Sora** [comment]
So you need to set the Bauble Type in Game seems like an error in the cfg delete the bhc config and tell me if it launches
